# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            ZhuoFu
tagline:          ''
description:      '此后如竟没有炬火，我便是唯一的光'
url:              newbility523.github.io
# baseurl:          ''

author:
  name:           'HuangZhuofu'
  url:            https://github.com/Newbility523

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate