# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty

# Setup
title:            Zhuo fu
tagline:          ''
description:      '此后如竟没有炬火，我便是唯一的光'
url:              newbility523.github.io
baseurl:          ''

author:
  name:           'HuangZhuofu'
  url:            https://github.com/Newbility523

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate