# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            ZhuoFu
tagline:          ''
description:      '此后如竟没有炬火，我便是唯一的光'
url:              newbility523.github.io
baseurl:          ''

author:
  name:           'HuangZhuofu'
  url:            https://github.com/Newbility523

paginate:         5
paginate_path:    /recent-notes/page:num/

# Custom vars
version:          2.1.22

github:
  repo:           https://github.com/poole/hyde

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

include:
  - "_html"

plugins:
  - jekyll-paginate

giscus:
  enabled: true
  repo: Newbility523/newbility523.github.io
  repo_id: R_kgDOG3tznA
  category: General
  category_id: DIC_kwDOG3tznM4C-oRr
  mapping: pathname
  strict: 1
  reactions_enabled: 1
  emit_metadata: 0
  input_position: bottom
  theme: preferred_color_scheme
  lang: en
